### ISSUE TITLE
App crashes on Android 12

### ISSUE THREAD

**Issue by erawhctim** [aghontpi/ad-silence#4]
Logcat error: 
```
                         E  Process: bluepie.ad_silence, PID: 32424
                         E  java.lang.IllegalArgumentException: bluepie.ad_silence: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE
                            or FLAG_MUTABLE be specified when creating a PendingIntent.
                         E  Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable,
                            e.g. if it needs to be used with inline replies or bubbles.
                         E      at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
                         E      at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
                         E      at android.app.PendingIntent.getActivity(PendingIntent.java:444)
                         E      at android.app.PendingIntent.getActivity(PendingIntent.java:408)
                         E      at e.h.c(:4)
                         E      at e.h.h(Unknown Source:0)
                         E      at bluepie.ad_silence.NotificationListener.onListenerConnected(Unknown Source:18)
                         E      at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2319)
                         E      at android.os.Handler.dispatchMessage(Handler.java:106)
                         E      at android.os.Looper.loopOnce(Looper.java:201)
                         E      at android.os.Looper.loop(Looper.java:288)
                         E      at android.app.ActivityThread.main(ActivityThread.java:7839)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Running on a Pixel 6; I can debug/install locally from the repo if needed, just lemme know.

**Comment by aghontpi** [comment]
thanks for testing this, I've made a possible fix based on the crash log and took a build.

- rename '.zip' to '.apk', 
- uninstall previous installations and install this one,

(can't upload apk files in comments)
[app-release.zip](https://github.com/aghontpi/ad-silence/files/7628389/app-release.zip)

**Comment by erawhctim** [comment]
Nice! It worked great to fix the crash 😎 

I noticed however that the actual app doesn't work to stop spotify ads 😞 I'll log another ticket for that; we can close this one.

**Comment by aghontpi** [comment]
glad it did'nt crash :laughing:, thanks for verifying :+1: .

**Comment by aghontpi** [comment]
ec5df7e6960a5f62b7088f36687b713a861d9cca fixes this issue.
